--- ansible-postgresql94-bdr/tasks/configure.yml

- name: Initialize new PostgreSQL BDR cluster on upstream server
  sudo: yes
  sudo_user: postgres
  command: "/usr/pgsql-9.4/bin/initdb -D {{ postgresql_datadir }} -A trust"

- name: Configure pg_hba.conf
  lineinfile:
    dest: "{{ postgresql_datadir }}/pg_hba.conf"
    state: present
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640
    line: "host    {{ item[0] }}     {{ postgresql_admin_user }}        {{ item[1] }}/32       trust"
  with_nested:
    - [ 'all', 'replication' ] 
    - [ "{{ postgresql_upstream }}", "{{ postgresql_downstream }}" ]

- name: Configure postgresql.conf
  lineinfile:
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    state: present
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640
    regexp: "{{ item.regexp }}"
    line: "{{ item.guc }}"
  with_items: postgresql_shared_guc

- name: Start PostgreSQL
  sudo: yes
  sudo_user: postgres
  command: "/usr/pgsql-9.4/bin/pg_ctl -D {{ postgresql_datadir }} start"

- name: Create demo database
  postgresql_db:
    name="{{ postgresql_bdr_database }}"
    state=present

- name: Configure upstream server postgresql.conf
  lineinfile:
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    state: present
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640
    line: "{{ item.guc }}"
  with_items: postgresql_upstream_guc
  when: ansible_default_ipv4.address == postgresql_upstream

- name: Configure downstream server postgresql.conf
  lineinfile:
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    state: present
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640
    line: "{{ item.guc }}"
  with_items: postgresql_downstream_guc
  when: ansible_default_ipv4.address == postgresql_downstream

- name: Final PostgreSQL restart
  sudo: yes
  sudo_user: postgres
  command: "/usr/pgsql-9.4/bin/pg_ctl -D {{ postgresql_datadir }} restart"
